SHOULD_RESTART_ADB = None
SHOULD_BUILD_NEW_APK = None
SHOULD_RECREATE_EXISTING_AVD = None
SHOULD_LAUNCH_AVD_SEQUENTIALLY = None
SHOULD_USE_ONLY_DEVICES_SPAWNED_IN_SESSION = None
SHOULD_RECORD_TESTS = None
SHOULD_RERUN_FAILED_TESTS = None

AVD_ADB_BOOT_TIMEOUT = None
AVD_SYSTEM_BOOT_TIMEOUT = None

IGNORED_DEVICE_LIST = []

ADB_SCAN_INTERVAL = None
ADB_CALL_BUFFER_SIZE = None
ADB_CALL_BUFFER_DELAY_BETWEEN_CMD = None

FLAKINESS_RERUN_COUNT = None

SDK_DIR = ""
AVD_DIR = ""
PROJECT_ROOT_DIR = ""
APK_DIR = ""
OUTPUT_DIR = ""

OUTPUT_SUMMARY_LOG_DIR = ""
OUTPUT_AVD_LOG_DIR = ""
OUTPUT_TEST_LOG_DIR = ""
OUTPUT_TEST_LOGCAT_DIR = ""
OUTPUT_TEST_RECORDINGS_DIR = ""
OUTPUT_STYLES_FOLDER_DIR = ""
OUTPUT_LOGCAT_HTML_DIR = ""
OUTPUT_INDEX_HTML_DIR = ""

DEVICE_VIDEO_STORAGE_DIR = ""
LOG_GENERATOR_DIR = ""

INSTRUMENTATION_RUNNER = ""
APP_PACKAGE = ""
APP_TEST_PACKAGE = ""
