class Settings:

    SHOULD_RESTART_ADB = None
    SHOULD_RECREATE_EXISTING_AVD = None
    SHOULD_LAUNCH_AVD_SEQUENTIALLY = None
    AVD_LAUNCH_SCAN_INTERVAL = None
    AVD_ADB_BOOT_TIMEOUT = None
    AVD_SYSTEM_BOOT_TIMEOUT = None

    SDK_DIR = ""
    AVD_DIR = ""
    OUTPUT_DIR = ""

    ANDROID_TEST_PACKAGE = ""
    ANDROID_APP_PACKAGE = ""
