class Settings:

    SHOULD_RESTART_ADB = None
    SHOULD_BUILD_NEW_APK = None
    SHOULD_RECREATE_EXISTING_AVD = None
    SHOULD_LAUNCH_AVD_SEQUENTIALLY = None
    SHOULD_USE_ONLY_DEVICES_SPAWNED_IN_SESSION = None
    AVD_LAUNCH_SCAN_INTERVAL = None
    AVD_ADB_BOOT_TIMEOUT = None
    AVD_SYSTEM_BOOT_TIMEOUT = None

    SDK_DIR = ""
    AVD_DIR = ""
    OUTPUT_DIR = ""
    PROJECT_ROOT_DIR = ""
    APK_DIR = ""

    INSTRUMENTATION_RUNNER = ""
